"""Stage 2 domain layer: models, the Stage 1 adapter, interfaces, exceptions."""

from .brief import TopicBrief
from .exceptions import (
    AssetValidationError,
    MetadataError,
    RenderError,
    ScriptGenerationError,
    ShortsConfigurationError,
    ShortsError,
    ShortsPipelineError,
    StageError,
    UploadError,
    VisualError,
    VoiceError,
)
from .interfaces import (
    LLMProvider,
    PipelineStage,
    StorageProvider,
    UploadProvider,
    VisualProvider,
    VoiceProvider,
)
from .models import (
    AssetIssue,
    AssetValidationReport,
    CaptionCue,
    GeneratedShort,
    RenderedVideo,
    Scene,
    ScenePlan,
    Script,
    ScriptScene,
    Severity,
    ThumbnailResult,
    TopicResearch,
    UploadResult,
    VideoMetadata,
    VisualAsset,
    VisualType,
    VoiceResult,
)

__all__ = [
    # adapter
    "TopicBrief",
    # interfaces
    "LLMProvider",
    "PipelineStage",
    "StorageProvider",
    "UploadProvider",
    "VisualProvider",
    "VoiceProvider",
    # models
    "AssetIssue",
    "AssetValidationReport",
    "CaptionCue",
    "GeneratedShort",
    "RenderedVideo",
    "Scene",
    "ScenePlan",
    "Script",
    "ScriptScene",
    "Severity",
    "ThumbnailResult",
    "TopicResearch",
    "UploadResult",
    "VideoMetadata",
    "VisualAsset",
    "VisualType",
    "VoiceResult",
    # exceptions
    "AssetValidationError",
    "MetadataError",
    "RenderError",
    "ScriptGenerationError",
    "ShortsConfigurationError",
    "ShortsError",
    "ShortsPipelineError",
    "StageError",
    "UploadError",
    "VisualError",
    "VoiceError",
]
